### ISSUE TITLE
目前存在杀毒软件报毒的问题

### ISSUE THREAD

**Issue by fattypanda** [SkywalkerJi/mdt#1]
如题

**Comment by SkywalkerJi** [comment]
可以使用python直接从Source code启动mdt.py

**Comment by fattypanda** [comment]
> 可以使用python直接从源代码启动mdt.py

 懂开发的可以这样弄，那些不懂的怕是环境都不会安装。（B站私信回复一下）

**Comment by SkywalkerJi** [comment]
> > 可以使用python直接从源代码启动mdt.py
> 
> 懂开发的可以这样弄，那些不懂的怕是环境都不会安装。（B站私信回复一下）

那就把杀毒软件添加信任吧。已经是直接调用win32基础api了，没有使用其他第三方dll。

**Comment by SkywalkerJi** [comment]
我试了下是win7的exe会被误报，win10的好像没问题。
