### ISSUE TITLE
抽卡界面支持

### ISSUE THREAD

**Issue by cbconne** [SkywalkerJi/mdt#17]
目前抽卡界面还不支持翻译，将来有支持计划吗？

**Comment by SkywalkerJi** [comment]
读取抽卡界面，需要对游戏进行注入，风险会比较高。（这里风险高的意思是这个游戏的作弊情况比我预想的要严重，也不知道官方后续会采取什么措施，但目前我还是认为启用本地反作弊是毫无经济性的行为）按现在的情况来说，确实游戏也没有办法检测注入行为。

或者另一种办法是用CV引擎进行识别。这种就是没有侵入性，但是我最近比较忙没有时间来写。

另外商店的卡表实际上是固定，可以直接在 [MDT-web](https://ygo.xn--uesr8qr0rdwk.cn/#/) 查到

**Comment by SkywalkerJi** [comment]
https://github.com/SkywalkerJi/mdt/releases/tag/v0.2.12

v0.2.12版本已经解决。如有需要可以重启issue。
