### ISSUE TITLE
等待检测状态时，点击提示区域会导致程序崩溃

### ISSUE THREAD

**Issue by yxrlz** [SkywalkerJi/mdt#21]
![QQ图片20220228231205](https://user-images.githubusercontent.com/4005042/156007580-34823c1b-7cb8-4ab5-bf02-f228a625045e.png)

**Comment by SkywalkerJi** [comment]
会在v0.2.12修复。
提的很及时，我刚准备发版。

**Comment by SkywalkerJi** [comment]
https://github.com/SkywalkerJi/mdt/releases/tag/v0.2.12

v0.2.12版本已经解决。如有需要可以重启issue。
