### ISSUE TITLE
卡片文本描述空格会变成换行

### ISSUE THREAD

**Issue by noirfy** [SkywalkerJi/mdt#23]
Win10， MDT v0.2.12

在查卡器文本描述页面有空格会变成换行，不知道本来是这样的还是真的文本处理有问题。

例如 海归坏兽 的④效果空格变成换行了
![pic1](https://i.bmp.ovh/imgs/2022/03/50456daf35c954dc.png)

再比如天霆号高达的描述第二行也换行了
![pic2](https://i.bmp.ovh/imgs/2022/03/0bef8e16a540d8f6.png)

**Comment by SkywalkerJi** [comment]
v0.2.13已处理。可以试用一下。

**Comment by noirfy** [comment]
感谢
