### ISSUE TITLE
[Feature request] 我希望我能够协助增加自动导入YDK卡包的功能，所以我先来占一个坑

### ISSUE THREAD

**Issue by chunibyo-wly** [SkywalkerJi/mdt#29]
**Is your feature request related to a problem? Please describe.**
否

**Describe the solution you'd like**
1. 作者仓库里面已经有两份数据库，我考虑使用python用的那一个数据库将YDK卡密转化成外文。
2. 如何判断客户端语言暂时还没想到解决办法。
3. 游戏内输入框点击与卡片选择应该是用最基础的图像模板匹配方案。

这里先占个坑，希望听一下作者的意见。

**Comment by SkywalkerJi** [comment]
我没懂你想用哪种方式导入.模拟MnK吗?

**Comment by chunibyo-wly** [comment]
您好，我准备用最粗暴最没效率的模拟点击方法。

**Comment by SkywalkerJi** [comment]
理论上可以.
ydk转换的部分要注意ydk是支持异图的,这部分卡密目前并不在card.json中.

**Comment by chunibyo-wly** [comment]
好的谢谢您

**Comment by SkywalkerJi** [comment]
我之前的想法是监听ctrl+v这个系统快捷键,每次触发粘贴时候自动将卡表中下一张卡塞进剪贴板.
这种应该比较好实现,,后面可以再改全自动.

**Comment by chunibyo-wly** [comment]
您说的对，那我先试着实现一下这个

**Comment by chunibyo-wly** [comment]
@SkywalkerJi 大佬您好，现有demo大致是这个样子【ydk 卡组导入 demo-哔哩哔哩】 https://b23.tv/oKPh2jY
图像识别的部分先硬编码了，主要先测试一下整个流程。

然后我发现md搜索机制会出现【检索某卡】的卡片排序前于那张卡，同时由于我只会取第一张所以会出现问题，所以这种需要使用额外处理（我还没想到有什么好办法）。

再就是一定得使用win32api吗，我这个部分的瓶颈不是在模拟上，所以可不可以使用更高级一点的操作包

最后就是大佬你有直接尝试去写内存吗

**Comment by SkywalkerJi** [comment]
写内存当然是可以的，一次性写入整个卡组。
但是k社没有进行服务器校验，导致可以写入并上传不合法的cid，然后就会游戏报错打不开deck界面。需要在写入前对非法cid进行拦截。但这样操作风险还是太高所以我没有写进去。
