### ISSUE TITLE
5月6日更新后mdt无法正常使用

### ISSUE THREAD

**Issue by A-new-b** [SkywalkerJi/mdt#35]
**Describe the bug**
如题
![图片](https://user-images.githubusercontent.com/43344034/167061550-31af50ae-21a6-40b8-b9ed-3e0ec08af8fc.png)
选中卡片后mdt无法正常翻译

**Comment by chunibyo-wly** [comment]
您好，可以给一下配置文件信息吗，我怀疑是我把代码改坏了

**Comment by chunibyo-wly** [comment]
经过测试，原因应该是内存位置变了，这个需要再重新寻找地址，暂时可以先使用**图形识别模式**

![image](https://user-images.githubusercontent.com/33208530/167065235-d92b8cde-57ed-4a07-9537-f004bc5948db.png)

受此影响自动添加卡组功能已经出问题

**Comment by ChibisukeDragon** [comment]
我使用的是旧的V0.2.12版本，也在5.6游戏更新后无法识别了。目前用图像识别方法

**Comment by SkywalkerJi** [comment]
今天游戏更新了客户端?
那晚上我更一版.

**Comment by RyoLee** [comment]
编辑卡组基址偏移可用组合为 GameAssembly.dll+0x01E99C18 [0xB8, 0x0, 0xF8, 0x1E0] + 0x2C
对局/回放(现在好像这俩是一个了?)可用组合为 GameAssembly.dll+0x01DBDC88 [0xB8, 0x10] + 0x4C
着急用的可以自己改(

**Comment by SkywalkerJi** [comment]
> 编辑卡组基址偏移可用组合为 GameAssembly.dll+0x01E99C18 [0xB8, 0x0, 0xF8, 0x1E0] + 0x2C 对局/回放(现在好像这俩是一个了?)可用组合为 GameAssembly.dll+0x01DBDC88 [0xB8, 0x10] + 0x4C 着急用的可以自己改(

刚准备找（

**Comment by SkywalkerJi** [comment]
https://github.com/SkywalkerJi/mdt/releases/tag/v0.2.16

release

**Comment by A-new-b** [comment]
非常感谢

**Comment by paradoxskin** [comment]
> 编辑卡组基址偏移可用组合为 GameAssembly.dll+0x01E99C18 [0xB8, 0x0, 0xF8, 0x1E0] + 0x2C 对局/回放(现在好像这俩是一个了?)可用组合为 GameAssembly.dll+0x01DBDC88 [0xB8, 0x10] + 0x4C 着急用的可以自己改(

想问一下内存位置运算是手推还是反编译dll函数看出来的
