### ISSUE TITLE
我现在保存卡组用不了

### ISSUE THREAD

**Issue by 1131204486** [SkywalkerJi/mdt#38]
没有反应

**Comment by SkywalkerJi** [comment]
版本号

**Comment by 1131204486** [comment]
> 版本号
mdt_v0.2.16

**Comment by 1131204486** [comment]
> 版本号



> 版本号

mdt_v0.2.16

**Comment by 1131204486** [comment]
> 版本号

mdt_v0.2.16

**Comment by SkywalkerJi** [comment]
> > 版本号
> 
> mdt_v0.2.16

昨天忘记测这个了,今天回去有空的话我改一下.

**Comment by 1131204486** [comment]
> > > 版本号
> > 
> > 
> > mdt_v0.2.16
> 
> 昨天忘记测这个了,今天回去有空的话我改一下.

2.16版本图像识别经常失灵需要重启，我就换回2.13，发现保存卡组也不行

**Comment by Frefreak** [comment]
保存不了+1，直接运行mdt_deck_reader.py报错:
```
Could not read memory at: 24, length: 4 - GetLastError: 299
{'error': '无法读取卡组信息'}
```
102行左右：https://github.com/SkywalkerJi/mdt/blob/85d8ebb6777aefc98cebcc90a6d203df4611e704/mdt_deck_reader.py#L57-L103

另外CHANGELOG记录v0.2.6版本由“保存卡组”改为“导出卡组”，目前游戏内仍然显示的是保存卡组。
diff 0.2.5 0.2.6:
![image](https://user-images.githubusercontent.com/7122156/168408914-19a1165d-0ff3-4399-b9ed-a2ae60666d05.png)

**Comment by SkywalkerJi** [comment]
[v0.2.17](https://github.com/SkywalkerJi/mdt/releases/tag/v0.2.17)

该功能暂时去除。卡组指针地址目前为动态。如果不对游戏进行注入可能需要改为图像识别后导出。

**Comment by SkywalkerJi** [comment]
[v0.2.18](https://github.com/SkywalkerJi/mdt/releases/tag/v0.2.18)

已修复，有问题可以重启issue。
