### ISSUE TITLE
图像模式下ydk导入失败

### ISSUE THREAD

**Issue by cbconne** [SkywalkerJi/mdt#46]
在图像模式下使用 ydk 导入会出现检索后鼠标移动到目标卡牌上直接跳走的情况，内存模式下正常。
没细看代码但猜可能是图像模式下识别速度不如内存模式导致的，可以考虑在 ydk 导入的时候自动切换到内存模式（或者在说明界面上说明使用 ydk 导入时切换到内存模式）

**Comment by chunibyo-wly** [comment]
您好，您说的对，确实是这个原因。我想办法修一下
