### ISSUE TITLE
UAC重加载代码错误

### ISSUE THREAD

**Issue by RyoLee** [SkywalkerJi/mdt#5]
[mdt.py#L196](https://github.com/SkywalkerJi/mdt/blob/714da29e918638991f96b024bf738b48bde97ece/mdt.py#L196)

这一行不需要

我原始代码[Gevjon-Observer.py#L171](https://github.com/RyoLee/Gevjon-Observer/blob/279757ca6817224ab325c343950a1178a55cb65b/Gevjon-Observer.py#L171)这里是为了在默认权限下启动UI程序[RyoLee/Gevjon](https://github.com/RyoLee/Gevjon/)

(UI和识别程序走命名管道通信,所以尽量给监听端的UI程序低权限)

**Comment by SkywalkerJi** [comment]
去除了。
