### ISSUE TITLE
6/10 v1.1.1 新卡包更新後新卡沒辦法翻譯

### ISSUE THREAD

**Issue by aaron988025** [SkywalkerJi/mdt#53]
6/10 v1.1.1 新卡包更新後修女系列的卡包都沒辦法翻譯

**Comment by wtof1996** [comment]
#52 如果急着用的话可以先单独下载hash.json覆盖data\hash.json即可使用
![屏幕截图 2022-06-10 223826](https://user-images.githubusercontent.com/5406275/173186077-304b0741-1718-44cd-9748-ced36805df4e.png)

**Comment by SkywalkerJi** [comment]
[v0.2.17](https://github.com/SkywalkerJi/mdt/releases/tag/v0.2.17)

**Comment by SkywalkerJi** [comment]
close，有问题可以重开。
