### ISSUE TITLE
無法正常儲存設置

### ISSUE THREAD

**Issue by Zhen-Bo** [SkywalkerJi/mdt#54]
只要我將MDT設置完後拉到雙螢幕中的第二個螢幕並且點及保存窗口位置時就會導致位置訊息無法被正確儲存(我記得以前可以正常儲存)
下此啟動時會顯示為預設位置,而且就算語言是設定zh-TW,他也會顯示簡體中文

**Comment by SkywalkerJi** [comment]
系统版本？

**Comment by Zhen-Bo** [comment]
Win11 21H2 最新版MDT
