### ISSUE TITLE
6月15日更新后内存模式失效

### ISSUE THREAD

**Issue by inpachi18** [SkywalkerJi/mdt#55]
6月15日版本更新后内存模式失效，图像模式正常工作

**Comment by SkywalkerJi** [comment]
游戏版本号?

**Comment by inpachi18** [comment]
1.1.2版本
6月15日更新

**Comment by 1183710222** [comment]
同失效问题，mdt版本 v0.2.16，在6月15日更新后内存模式失效，图像识别仍可使用

**Comment by 494559430** [comment]
感觉好麻烦啊 每次小更新都会失效

**Comment by kamuxiy** [comment]
mdt版本0.2.18
游戏版本1.1.2
也是内存模式失效

**Comment by RyoLee** [comment]
https://github.com/RyoLee/Gevjon-Observer/commit/5c18cdb1283c9d6b33c1eed345e9f734db27da42

参考这个修改一下基址和偏移就好了,感觉是不是要抽时间做个怎么自行用CE提取的说明文档好些

**Comment by SkywalkerJi** [comment]
https://github.com/SkywalkerJi/mdt/releases/tag/v0.2.19
