### ISSUE TITLE
v.2.19 保存卡组功能主卡组导出显示为0

### ISSUE THREAD

**Issue by ee07b415** [SkywalkerJi/mdt#56]
windows 10 home 64位操作系统，2022/06/15 使用mdt v0.2.19 管理员模式运行.exe文件保存卡组，在.txt文件中只有额外卡组正确，主卡组显示为0

**Comment by ee07b415** [comment]
游戏是英文界面

**Comment by SkywalkerJi** [comment]
导出文件中主卡组没有卡吗？还是有卡但计数为0。

**Comment by SkywalkerJi** [comment]
https://github.com/SkywalkerJi/mdt/releases/tag/v0.2.20
