### ISSUE TITLE
English name missing for cid 15888 and 15889

### ISSUE THREAD

**Issue by zealyahweh** [SkywalkerJi/mdt#6]
导致抛exception说找不到该卡

**Comment by SkywalkerJi** [comment]
看了下15879-15891这批卡都没有。之后别的数据补一下。

**Comment by SkywalkerJi** [comment]
跑了一下，还有一堆卡信息缺失，尴尬。还是连ygopro的数据好了。

<details>
   <summary>列表</summary>
4031
4035
4053
4076
4081
4082
4083
4093
4099
4109
4112
4114
4122
4124
4128
4129
4132
4134
4136
4140
4141
4143
4144
4146
4147
4150
4151
4156
4158
4159
4169
4170
4173
4180
4182
4183
4185
4186
4187
4188
4189
4190
4191
4193
4194
4196
4197
4201
4202
4203
4209
4210
4211
4212
4222
4225
4228
4231
4233
4234
4235
4237
4238
4244
4245
4246
4248
4249
4252
4256
4259
4260
4265
4266
4267
4269
4270
4277
4279
4283
4289
4290
4291
4301
4304
4406
4410
4417
4419
4424
4427
4429
4437
4438
4440
4441
4442
4447
4449
4452
4455
4456
4457
4458
4461
4462
4463
4466
4470
4478
4482
4489
4491
4492
4495
4500
4505
4509
4510
4516
4524
4528
4531
4534
4536
4541
4542
4554
4562
4564
4572
4577
4582
4583
4584
4585
4590
4593
4594
4595
4596
4598
4601
4602
4607
4625
4628
4629
4631
4635
4639
4640
4646
4651
4654
5083
5297
5925
5929
6533
6534
6713
6715
6716
6717
6719
6788
6958
6959
7055
7237
7374
7375
7440
7505
7510
7511
7654
7992
7993
8610
8611
8772
8776
8868
8869
8931
9017
9247
9248
9850
9851
10112
10113
10321
10322
10685
10685
10828
10828
10845
10846
11124
11124
11306
11455
11456
12045
12046
12732
12733
12996
13122
13302
13347
13348
13453
14048
14049
14235
14236
14237
14335
14364
14384
14385
14438
14529
14737
14738
14783
14784
14785
14791
14796
14797
14950
14954
14955
14960
14961
14962
14963
15576
15584
15689
15780
15827
15891
16046
16047
16184
16188
16189
16283
16284
16306
16466
16619
16620
16621
16622
16623
16623
16624
16624
16625
16625
16626
16626
16627
16627
16628
16628
16629
16629
16630
16630
16631
16631
16632
16632
16633
16633
16634
16634
16645
16646
16647
16648
16649
16650
16651
16652
16723
16724
16725
16726
16727
16728
16729
16730
16731
16732
16733
16734
16735
16736
16737
16738
16739
16740
16741
16742
16743
16744
16745
16746
16747
16748
16749
16750
16751
16752
16753
16754
16755
16756
16757
16758
16759
16801
16802
16806
16807
16808
16809
16810
16811
16812
16813
16814
16815
16816
16817
16818
16819
16820
16821
16822
16823
16824
16825
16826
16827
16828
16829
16830
16831
16832
16833
16834
16835
16836
16837
16838
16839
16840
16841
16842
16843
16844
16845
16846
16847
16848
16849
16850
16851
16852
16853
16854
16855
16856
16857
16858
16859
16860
16861
16862
16863
16864
16865
16866
16867
16868
16869
16870
16871
16872
16873
16874
16875
16876
16877
16878
16879
16880
16881
16882
16883
16884
16885
16936
16936
16937
16937
16938
16938
16939
16939
16940
16940
16941
16941
16942
16942
16943
16943
16944
16944
16945
16945
16946
16946
16947
16952
16952
17031
17033
17034
17035
17036
17037
17038
17039
17040
17041
17042
17043
17044
17045
17046
17047
17048
17049
17050
17051
17052
17053
17054
17055
17056
17057
17058
17059
17062
17063
17064
17065
17066
17067
17068
17069
17070
17103
17104
17105
17106
17107
17108
17109
17110
17111
17112
17113
17114
17115
17116
17117
17118
17119
17120
17121
17122
17123
17124
17125
17126
17127
17128
17129
17130
17131
17132
17133
17134
17135
17136
17137
17138
17139
17140
17141
17142
17143
17144
17145
17146
17147
17148
17149
17150
17151
17152
17153
17154
17155
17156
17157
17158
17159
17160
17161
17162
17163
17164
17165
17166
17167
17168
17169
17170
17171
17172
17173
17174
17175
17176
17177
17178
17179
17180
17181
17182
17183
17184
17185
17186
17187
17188
17189
17190
17191
17267
17344
17345
</details>

**Comment by SkywalkerJi** [comment]
v0.2.2已解决。
先close，之后讨论可以在 #8
