### ISSUE TITLE
8月5日更新后内存识别模式失效

### ISSUE THREAD

**Issue by pcpg12138** [SkywalkerJi/mdt#60]
在8月5日更新后，内存识别模式失效，只能使用图像模式

**Comment by RShock** [comment]
我这边对战图像也失效了，因为对战ui有改动

**Comment by SkywalkerJi** [comment]
只有对战ui有改动吗。

**Comment by RShock** [comment]
组卡和详情都没有出问题

**Comment by SkywalkerJi** [comment]
https://github.com/SkywalkerJi/mdt/releases/tag/v0.2.22

改了一部分

**Comment by SkywalkerJi** [comment]
https://github.com/SkywalkerJi/mdt/releases/tag/v0.2.23
