### ISSUE TITLE
11月9日更新后内存识别模式失效

### ISSUE THREAD

**Issue by paradoxskin** [SkywalkerJi/mdt#68]

**Comment by JairPeng** [comment]
等大佬更新解决中

**Comment by pxly** [comment]
图像识别模式在对战中不能适用

**Comment by paradoxskin** [comment]
找到了最新的偏移量公式
[对战+回放](https://github.com/paradoxskin/mdt/commit/f082d1ab23e99497974e8806de829054a80d8dda)(这两个好像共用了，原来的对战还留着
[卡组](https://github.com/paradoxskin/mdt/commit/c3a49ef733cf716793f87aa4e126a04b9c68a126)
**note: 我把所有py文件里的[空格换成了tab](https://github.com/paradoxskin/mdt)**

**Comment by paradoxskin** [comment]
> 找到了最新的偏移量公式
> [对战+回放](https://github.com/paradoxskin/mdt/commit/f082d1ab23e99497974e8806de829054a80d8dda)(这两个好像共用了，原来的对战还留着
> [卡组](https://github.com/paradoxskin/mdt/commit/c3a49ef733cf716793f87aa4e126a04b9c68a126)
> 
> **note: 我把所有py文件里的[空格换成了tab](https://github.com/paradoxskin/mdt)**
> 

搞错了，oppo是对手卡组，对战和回放都是战斗界面

**Comment by Iridescent-me** [comment]
大佬是不是在忙别的事没空弄这边
